version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: estoque_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d
    command: >
      bash -c "apt-get update && apt-get install -y libpq-dev libzip-dev zip unzip &&
      docker-php-ext-install pdo pdo_pgsql zip &&
      a2enmod rewrite &&
      apache2-foreground"
    networks:
      - estoque_network

  db:
    image: postgres:15
    container_name: estoque_db
    restart: always
    environment:
      POSTGRES_DB: estoque
      POSTGRES_USER: admin        # Alterado: novo usuário root
      POSTGRES_PASSWORD: password # Alterado: nova senha root
      POSTGRES_MULTIPLE_DATABASES: estoque  # Define banco adicional
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh  # Script para criar usuário adicional
    networks:
      - estoque_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: estoque_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - estoque_network

volumes:
  postgres_data:

networks:
  estoque_network:
    driver: bridge
