version: '3.8'

services:
  php:
    image: ubuntu:22.04
    container_name: estoque_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PHP_INI_SCAN_DIR=/usr/local/etc/php/custom.d
    command: >
      "apt-get update && apt-get install -y libpq-dev libzip-dev zip unzip &&
      docker-php-ext-install pdo pdo_pgsql zip &&
      a2enmod rewrite &&
      service apache2 restart &&
      sed -i 's/sua_senha_aqui/${POSTGRES_PASSWORD}/g' /var/www/html/config/db.php &&
      sed -i 's/localhost/db/g' /var/www/html/config/db.php &&
      apache2-background -k start &&"
    networks:
      - estoque_network

  db:
    image: postgres:15
    container_name: estoque_db
    restart: always
    environment:
      POSTGRES_DB: estoque
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - estoque_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: estoque_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - estoque_network

volumes:
  postgres_data:

networks:
  estoque_network:
    driver: bridge
